deployments:
  MyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  xMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  aMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  sMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  bMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  nMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  mMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  lMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  mMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  jMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  hMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  alMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  mamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  xmamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  amamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  smamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  bmamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  nmamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  mmamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  lmamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  mmamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  jmamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  hmamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  almamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  mamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  xmamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  amamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  smamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  bmamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  nmamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  mmamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  lmamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  mmamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  jmamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  hmamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  almamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  mammamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  xmammamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  amammamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  smammamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  bmammamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  nmammamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  mmammamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  lmammamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  mmammamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  jmammamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  hmammamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  almammamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true


  mamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  xmamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  amamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  smamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  bmamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  nmamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  mmamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  lmamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  mmamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  jmamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  hmamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  almamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  mammamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  xmammamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  amammamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  smammamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  bmammamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  nmammamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  mmammamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  lmammamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  mmammamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  jmammamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  hmammamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  almammamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  mammamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  xmammamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  amammamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  smammamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  bmammamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  nmammamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  mmammamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  lmammamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  mmammamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  jmammamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  hmammamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  almammamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  mammammamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  xmammammamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  amammammamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  smammammamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  bmammammamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  nmammammamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  mmammammamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  lmammammamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  mmammammamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  jmammammamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  hmammammamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  almammammamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
true
