deployments:
  MyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  xMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  aMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  sMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  bMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  nMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  mMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  lMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  mMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  jMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  hMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  alMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  mamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  xmamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  amamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true

  smamMyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000 
    auto_deploy_on_commits:
      true
