deployments:
  MyApp:
    filename:
      ./Dockerfile
    context_path:
      ./
    port_forwarding:
      80:3000
    depends_on:
      - SALES_API:
          app: api-sales/master
      - PRODUCTS_API:
          app: api-products
      - SALES_APaI:
          app: api-sales/masater
      - PRODUCTS_aAPI:
          app: api-prodaucts
